[versions]
kotlin = "1.9.22"
asm = "9.6"
dexlib2 = "3.0.3"
assertj = "3.24.2"
junit-jupiter = "5.10.1"

# Android Tools / Layoutlib (versions must match Paparazzi's tested combinations)
android-tools = "31.13.2"
layoutlib = "16.1.1"
layoutlib-api = "31.13.2"

# Other
kxml2 = "2.3.0"
slf4j = "1.7.36"

[libraries]
# Bytecode
asm = { module = "org.ow2.asm:asm", version.ref = "asm" }
asm-commons = { module = "org.ow2.asm:asm-commons", version.ref = "asm" }
dexlib2 = { module = "com.android.tools.smali:smali-dexlib2", version.ref = "dexlib2" }

# Android Tools / Layoutlib
android-tools-common = { module = "com.android.tools:common", version.ref = "android-tools" }
android-tools-sdk-common = { module = "com.android.tools:sdk-common", version.ref = "android-tools" }
android-tools-layoutlib = { module = "com.android.tools.layoutlib:layoutlib", version.ref = "layoutlib" }
android-tools-layoutlib-api = { module = "com.android.tools.layoutlib:layoutlib-api", version.ref = "layoutlib-api" }
android-tools-layoutlib-resources = { module = "com.android.tools.layoutlib:layoutlib-resources", version.ref = "layoutlib" }
android-tools-layoutlib-runtime = { module = "com.android.tools.layoutlib:layoutlib-runtime", version.ref = "layoutlib" }
android-tools-external-intellij-core = { module = "com.android.tools.external.com-intellij:intellij-core", version.ref = "android-tools" }

# XML
kxml2 = { module = "net.sf.kxml:kxml2", version.ref = "kxml2" }

# Logging
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }

# Testing
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit-jupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
